### ISSUE TITLE
Failed outgoing ping prints a stacktrace in console

### ISSUE THREAD

**Issue by CDAGaming** [TheLunarFrog/LagMeter#8]
[20:10:39 WARN]: [LagMeter] Plugin LagMeter v1.18.0-SNAPSHOT generated an exception while executing task 40
java.lang.ArrayIndexOutOfBoundsException: 5
        at com.webkonsept.minecraft.lagmeter.LagMeter$5.run(LagMeter.java:1050) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot-latest.jar:git-Paper-1174]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [PaperSpigot-latest.jar:git-Paper-1174]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [PaperSpigot-latest.jar:git-Paper-1174]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by TheLunarFrog** [comment]
@CDAGaming What OS are you running? This appears to be an OS-specific issue.

**Comment by CDAGaming** [comment]
I'm running it and the server(Paperspigot 1.12.1) on Linux

It does work on window, but passes an exception on linux

**Comment by TheLunarFrog** [comment]
@CDAGaming What Linux distribution I meant

**Comment by CDAGaming** [comment]
Ubuntu 16.10

**Comment by CDAGaming** [comment]
Any News? @TheLunarFrog

**Comment by TheLunarFrog** [comment]
@CDAGaming I have a bandage fix that will go out tonight and if you notice anything strange, post the log here.

**Comment by TheLunarFrog** [comment]
A new build should be up on my build server shortly. Please comment on this issue and tag me if you experience any more issues with this.

Thanks

**Comment by CDAGaming** [comment]
One thing i should also note since you have a build server @TheLunarFrog is to make a Readme.md perhaps stating it, and maybe some other info too

Testing Fix Now, will report if fixed

**Comment by CDAGaming** [comment]
![2017-08-16 3](https://user-images.githubusercontent.com/16328918/29395766-eb875c46-82d8-11e7-9edf-de10d37a8528.png)
Unexpected Output, but no more console spam at least @TheLunarFrog

**Comment by TheLunarFrog** [comment]
@CDAGaming Ah, I see what's going on... A change I made a while back but never finished seems to have made its way into the stable branch.

Bandage fix no longer needed. Next build won't do that anymore, it'll display what it's supposed to.
